### PR TITLE
Richel's iOS GA PreWork

### PR DESCRIPTION
**Pull request by Richel325**
So excited to start class and to keep learning!

### CODE REVIEW

**Comment by jeff-boykin** [comment]
Hey @Richel325 - we're glad to have you! However, check out the [precourse assignment submission instructions one more time here](https://github.com/generalassembly-studio/iOSI-precourse-onboarding/blob/master/01-task/project.md). 

I've copied the specifics below.

### Submission
Use your newfound terminal & git knowledge to submit your work!

1. Push your local edits up to your remote fork. This will copy your local files to your online github fork.
2. [Use the following form to send us the link to your fork, so we can review your materials!](http://goo.gl/forms/onJ8DOil8ftWYySJ2)

* Note: *Make sure you've re-titled your saved playground and app files with your full name!*

**Comment by Richel325** [comment]
Hi Jeff!

Thanks for reaching out. I submitted my pre-work through the Google Forms link also/already. Did I do that incorrectly?

I appreciate your help!
Richel 

On Oct 5, 2016, at 2:39 PM, Jeff Boykin <notifications@github.com> wrote:

Hey @Richel325 - we're glad to have you! However, check out the precourse assignment submission instructions one more time here.

I've copied the specifics below.

Submission

Use your newfound terminal & git knowledge to submit your work!

Push your local edits up to your remote fork. This will copy your local files to your online github fork.
Use the following form to send us the link to your fork, so we can review your materials!

Note: Make sure you've re-titled your saved playground and app files with your full name!

**Comment by jeff-boykin** [comment]
@Richel325 Excellent! Nope, just checked and looks like you followed directions perfectly. I'm going to go ahead and close this pull request, but we'll evaluate your prework based on the link you submitted to your own fork. Make sense?

Cheers!

**Comment by Richel325** [comment]
Hi Jeff - that makes sense! Thanks again for your help!

All best,
Richel

**Pull request closed without merging**
